spring.application.name=territory-game
server.port=${PORT:8080}
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s
spring.web.resources.cache.cachecontrol.max-age=1h
